### ISSUE TITLE
MolPay logo will break the SSL symbols

### ISSUE THREAD

**Issue by shaifful** [MOLPay/OpenCart2.0_Plugin#3]
Hi bro, would you add in the Molpay Logo Directly in the Plugins?  It was a bit annoying when the MolPay logo breaks the SSL logo in the checkout and also in the administrator.

It is also some way missing in sale/order/info in admin page when the code becomes like this.
http://www.molpay.com/molpay%3C/td%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/tr%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C/table%3E%20%20%20%20%20%20%20%20%20%20%3C/div%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=

**Comment by vespazwan** [comment]
![opencart2 0_seamless](https://cloud.githubusercontent.com/assets/6263224/5717583/333763e0-9b3e-11e4-8cbc-214294083ddf.jpg)
